services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finanzas-sql
    env_file: .env
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: .
    container_name: finanzas-api
    env_file: .env
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__Default: ${CONNECTION_STRING}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  sql_data:
